### ISSUE TITLE
When you plain to release your first release?

### ISSUE THREAD

**Issue by stojankukrika** [toondaey/laravel-bulksmsnigeria.com#1]
Hi, I like to be your fist user of this package. So when you plan to release it?

**Comment by toondaey** [comment]
Hi @stojankukrika, the package will be released soon. I'm still working on finishing the unit testing, then it'll be released. Thanks.

**Comment by stojankukrika** [comment]
Can you release version without that? Some kind of beta or something? I like to test it in "real life" so need it very much.

**Comment by toondaey** [comment]
Thanks @stojankukrika for the push, the first release has officially been published.

**Comment by stojankukrika** [comment]
Thank you bro!
